<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="assets/css/index.css">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div id="app"></div>
    </div>
<script type="text/javascript" src="assets/js/index.js"></script>
</body>
</html>
